version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 6500:5432
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgresdb:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: password123

volumes:
  postgresdb:
